export const CANCELLATION_SCREEN_PREFIX = 'cancellationScreen/';

export const CANCEL_RESERVATION_REQUESTED = `${CANCELLATION_SCREEN_PREFIX}CANCEL_RESERVATION_REQUESTED`;
export const CANCEL_RESERVATION_SUCCEEDED = `${CANCELLATION_SCREEN_PREFIX}CANCEL_RESERVATION_SUCCEEDED`;
export const CANCEL_RESERVATION_FAILED = `${CANCELLATION_SCREEN_PREFIX}CANCEL_RESERVATION_FAILED`;

export const ACTIVE_RESERVATIONS_REQUESTED = `${CANCELLATION_SCREEN_PREFIX}ACTIVE_RESERVATIONS_REQUESTED`;
export const ACTIVE_RESERVATIONS_SUCCEEDED = `${CANCELLATION_SCREEN_PREFIX}ACTIVE_RESERVATIONS_SUCCEEDED`;
export const ACTIVE_RESERVATIONS_FAILED = `${CANCELLATION_SCREEN_PREFIX}ACTIVE_RESERVATIONS_FAILED`;
