export const SLOTS_SCREEN_PREFIX = 'slotsScreen/';

export const PARKING_SLOTS_REQUESTED = `${SLOTS_SCREEN_PREFIX}PARKING_SLOTS_REQUESTED`;
export const PARKING_SLOTS_SUCCEEDED = `${SLOTS_SCREEN_PREFIX}PARKING_SLOTS_SUCCEEDED`;
export const PARKING_SLOTS_FAILED = `${SLOTS_SCREEN_PREFIX}PARKING_SLOTS_FAILED`;

export const RESERVED_SLOTS_REQUESTED = `${SLOTS_SCREEN_PREFIX}RESERVED_SLOTS_REQUESTED`;
export const RESERVED_SLOTS_SUCCEEDED = `${SLOTS_SCREEN_PREFIX}RESERVED_SLOTS_SUCCEEDED`;
export const RESERVED_SLOTS_FAILED = `${SLOTS_SCREEN_PREFIX}RESERVED_SLOTS_FAILED`;

export const SLOT_RESERVATION_REQUESTED = `${SLOTS_SCREEN_PREFIX}SLOT_RESERVATION_REQUESTED`;
export const SLOT_RESERVATION_SUCCEEDED = `${SLOTS_SCREEN_PREFIX}SLOT_RESERVATION_SUCCEEDED`;
export const SLOT_RESERVATION_FAILED = `${SLOTS_SCREEN_PREFIX}SLOT_RESERVATION_FAILED`;
