export const FEEDBACK_SCREEN_PREFIX = 'slotsScreen/';

export const SUBMIT_FEEDBACK_REQUESTED = `${FEEDBACK_SCREEN_PREFIX}SUBMIT_FEEDBACK_REQUESTED`;
export const SUBMIT_FEEDBACK_SUCCEEDED = `${FEEDBACK_SCREEN_PREFIX}SUBMIT_FEEDBACK_SUCCEEDED`;
export const SUBMIT_FEEDBACK_FAILED = `${FEEDBACK_SCREEN_PREFIX}SUBMIT_FEEDBACK_FAILED`;
