export const PARKING_AREAS_SCREEN_PREFIX = 'parkingAreasScreen/';

export const PARKING_AREAS_REQUESTED = `${PARKING_AREAS_SCREEN_PREFIX}PARKING_AREAS_REQUESTED`;
export const PARKING_AREAS_SUCCEEDED = `${PARKING_AREAS_SCREEN_PREFIX}PARKING_AREAS_SUCCEEDED`;
export const PARKING_AREAS_FAILED = `${PARKING_AREAS_SCREEN_PREFIX}PARKING_AREAS_FAILED`;
