export const ADMIN_SCREENS_PREFIX = 'admin/';

export const ALL_CANCELLATIONS_REQUESTED = `${ADMIN_SCREENS_PREFIX}ALL_CANCELLATIONS_REQUESTED`;
export const ALL_CANCELLATIONS_SUCCEEDED = `${ADMIN_SCREENS_PREFIX}ALL_CANCELLATIONS_SUCCEEDED`;
export const ALL_CANCELLATIONS_FAILED = `${ADMIN_SCREENS_PREFIX}ALL_CANCELLATIONS_FAILED`;

export const ALL_FEEDBACK_REQUESTED = `${ADMIN_SCREENS_PREFIX}ALL_FEEDBACK_REQUESTED`;
export const ALL_FEEDBACK_SUCCEEDED = `${ADMIN_SCREENS_PREFIX}ALL_FEEDBACK_SUCCEEDED`;
export const ALL_FEEDBACK_FAILED = `${ADMIN_SCREENS_PREFIX}ALL_FEEDBACK_FAILED`;

export const ALL_RESERVATIONS_REQUESTED = `${ADMIN_SCREENS_PREFIX}ALL_RESERVATIONS_REQUESTED`;
export const ALL_RESERVATIONS_SUCCEEDED = `${ADMIN_SCREENS_PREFIX}ALL_RESERVATIONS_SUCCEEDED`;
export const ALL_RESERVATIONS_FAILED = `${ADMIN_SCREENS_PREFIX}ALL_RESERVATIONS_FAILED`;

export const ALL_USERS_REQUESTED = `${ADMIN_SCREENS_PREFIX}ALL_USERS_REQUESTED`;
export const ALL_USERS_SUCCEEDED = `${ADMIN_SCREENS_PREFIX}ALL_USERS_SUCCEEDED`;
export const ALL_USERS_FAILED = `${ADMIN_SCREENS_PREFIX}ALL_USERS_FAILED`;

export const FEEDBACK_REPLY_REQUESTED = `${ADMIN_SCREENS_PREFIX}FEEDBACK_REPLY_REQUESTED`;
export const FEEDBACK_REPLY_SUCCEEDED = `${ADMIN_SCREENS_PREFIX}FEEDBACK_REPLY_SUCCEEDED`;
export const FEEDBACK_REPLY_FAILED = `${ADMIN_SCREENS_PREFIX}FEEDBACK_REPLY_FAILED`;
