export const EMAIL_VERIFICATION_REDIRECTION_URL = 'http://localhost:8080/';

export const AUTH_PREFIX = 'auth/';

export const USER_RESGITRATION_REQUESTED = `${AUTH_PREFIX}USER_RESGITRATION_REQUESTED`;
export const USER_RESGITRATION_SUCCEEDED = `${AUTH_PREFIX}USER_RESGITRATION_SUCCEEDED`;
export const USER_RESGITRATION_FAILED = `${AUTH_PREFIX}USER_RESGITRATION_FAILED`;

export const USER_LOGIN_REQUESTED = `${AUTH_PREFIX}USER_LOGIN_REQUESTED`;
export const USER_LOGIN_SUCCEEDED = `${AUTH_PREFIX}USER_LOGIN_SUCCEEDED`;
export const USER_LOGIN_FAILED = `${AUTH_PREFIX}USER_LOGIN_FAILED`;
